### ISSUE TITLE
add collection vendimias

### ISSUE THREAD

**Issue by Japoivvb** [Abel1002/viticulture#8]
1. after each vendimia is executed a new document must be saved in a new collection called vendimias with fields
- counter(starting from 1) 
- datetime(showing current date time when vendimia was processed)

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb + details

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by Abel1002** [comment]
<img width="959" alt="Evidencia" src="https://github.com/Abel1002/viticulture/assets/147430925/fc27ee0a-07a6-45d1-954e-5976b6aa223a">

**Comment by Japoivvb** [comment]
working but entity Contador is not used and no required in this design
